# Generated by Django 5.2.5 on 2025-08-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films/', verbose_name='Постер'),
        ),
    ]
